export const artists = [
    {
        name: 'Arijit Singh',
        nationality: 'Indian',
        age: 36,
        id: '123',
        profileUrl: 'https://img.etimg.com/thumb/width-640,height-480,imgsize-47012,resizemode-75,msid-100076153/magazines/panache/should-i-leave-video-of-arijit-singh-gently-schooling-eager-fan-goes-viral-on-the-internet/arijit-singh-2.jpg',
        songs: [
            {
                id: '123',
                title: 'Tum Hi Ho',
                composer: 'Mithoon',
                producer: 'Bhushan Kumar',
                productionDate: '08-JUN-2013',
                awards: 'Best Playback Singer(Male) 2014, Best song of the year 2014, Best Lyricist 2014',
                lyrics: [
                    'Hum Tere Bin Ab Reh Nahi Sakte',
                    'Tere Bina Kya Wajood Mera',
                    'Hum Tere Bin Ab Reh Nahi Sakte',
                    'Tere Bina Kya Wajood Mera',
                    '',
                    'Tujhse Juda Agar Ho Jayenge',
                    'Toh Khud Se Hi Ho Jayenge Juda',
                    '',
                    'Kyunki Tum Hi Ho Ab Tum Hi Ho',
                    'Zindagi Ab Tum Hi Ho',
                    'Chain Bhi Mera Dard Bhi',
                    'Meri Aashiqui Ab Tum Hi Ho',
                    '',
                    'Tera Mera Rishta Hai Kaisa',
                    'Ik Pal Door Gawara Nahi',
                    'Tere Liye Har Roj Hai Jeete',
                    'Tujhko Diya Mera Waqt Sabhi',
                    '',
                    'Koyi Lamha Mera Na Ho Tere Bina',
                    'Har Saans Pe Naam Tera',
                    '',
                    'Kyunki Tum Hi Ho Ab Tum Hi Ho',
                    'Zindagi Ab Tum Hi Ho',
                    'Chain Bhi Mera Dard Bhi',
                    'Meri Aashiqui Ab Tum Hi Ho',
                    '',
                    'Tumhi Ho Tumhi Ho',
                    '',
                    'Tere Liye Hi Jiya Main',
                    'Khud Ko Jo Yun De Diya Hai',
                    'Teri Wafa Ne Mujhko Sambhala',
                    'Saare Ghamon Ko Dil Se Nikala',
                    '',
                    'Tere Sath Mera Hai Naseeb Juda',
                    'Tujhe Paake Adhoora Na Raha Hmm..',
                    '',
                    'Kyunki Tum Hi Ho Ab Tum Hi Ho',
                    'Zindagi Ab Tum Hi Ho',
                    'Chain Bhi Mera Dard Bhi',
                    'Meri Aashiqui Ab Tum Hi Ho',
                    '',
                    'Kyunki Tum Hi Ho Ab Tum Hi Ho',
                    'Zindagi Ab Tum Hi Ho',
                    'Chain Bhi Mera Dard Bhi',
                    'Meri Aashiqui Ab Tum Hi Ho',
                ]
            },
            {
                id: '234',
                title: 'Chaleya',
                composer: 'Anirudh Ravichander',
                producer: 'Bhushan Kumar',
                productionDate: '10-JAN-2023',
                awards: 'nandi',
                lyrics: [
                    'Ishq Mein Dil Bana Hai',
                    'Ishq Mein Dil Fanna Hai Ho',
                    '',
                    'Mita De Ya Bana De',
                    'Maine Tujhko Chuna Hai Ho Ho',
                    '',
                    'Tere Saare Rang Odh Ke Dhang Odh Ke',
                    'Tera Hua Main Sabko Chhod Ke Ho Ho Ho',
                    'Ishq Ni Karna Naap Tol Ke Raaj Khol Ke',
                    'Aaya Hoon Main Sabko Bol Ke Ho',
                    '',
                    'Oh Main Taan Chaleya Teri Oar',
                    'Tera Chaleya Hai Zor',
                    'Tera Hoya Main Yaar Ve',
                    'Bhuleya Ae Sansaar Ve',
                    '',
                    'Chaleya Teri Oar',
                    'Tera Chaleya Hai Zor',
                    'Tera Hoya Main Yaar Ve',
                    'Bhuleya Ae Sansaar Ve',
                    '',
                    'Jag Tere Liye Chhodiya',
                    'Dil Tere Sang Jodiya',
                    'Ab Tera Main Toh Ho Gaya',
                    'Paa Ke Tujhe Main Kho Gaya',
                    '',
                    'Jag Tere Liye Chhodiya',
                    'Dil Tere Sang Jodiya',
                    'Ab Tera Main Toh Ho Gaya',
                    'Paa Ke Tujhe Main Kho Gaya',
                    'Kho Gaya Haan',
                    '',
                    'Ishq Mein Dil Bana Hai',
                    'Ishq Mein Dil Fanna Hai Ho',
                    'Ho Ho Ho',
                    '',
                    'Hansa De Ya Rula De',
                    'Maine Tujhko Chuna Hai Oh',
                    'Oh Ho Ho',
                    '',
                    'Duniya Kehti',
                    'Ishq Bhool Hai Befizool Hai',
                    'Humko Toh Dil Se',
                    'Kubool Hai Oh Oh Ho Ho',
                    '',
                    'Tujhme Dikhta',
                    'Rabb Ka Noor Hai Ek Suroor Hai',
                    'Tu Hai Apna Yeh Guroor Hai Oh',
                    'Oh Oh Ho',
                    '',
                    'Ve Main Taan Chaliya Teri Oar',
                    'Tera Chaleya Hai Zor',
                    'Teri Hoyi Main Yaar Ve',
                    'Bhuleya Ae Sansar Ve',
                    '',
                    'Chaleya Teri Oar',
                    'Tera Chaleya Hai Zor',
                    'Teri Hoyi Main Yaar Ve',
                    'Bhuleya Ae Sansar Ve',
                    '',
                    'Tu Ishq-e-Khwab Khwaab Sa Hai',
                    'Mera Behisaab Sa Hai',
                    'Tere Labb Choom Loon Main',
                    'Urdu Ki Kitaab Sa Hai',
                    '',
                    'Ishq-e-Khwab Khwaab Sa Hai',
                    'Mera Behisaab Sa Hai',
                    'Tere Labb Choom Loon Main',
                    'Urdu Ki Kitaab Sa Hai',
                    '',
                    'Jag Tere Liye Chhodiya',
                    'Ishq Mein Dil Fanna Hai',
                    'Dil Tere Sang Jodiya',
                    'Ishq Mein Dil Fanna Hai Ho Ho',
                    '',
                    'Ab Tera Main Toh Ho Gaya',
                    'Paa Ke Tujhe Main Kho Gaya',
                    'Jag Tere Liye Chhodiya',
                    'Mita De Ya Bana De',
                    '',
                    'Dil Tere Sang Jodiya',
                    'Maine Tujhko Chuna Hai Ho Ho',
                    'Paa Ke Tujhe Main Kho Gaya',
                    'Kho Gaya Haan',
                ]
            },
            {
                id: '345',
                title: 'Hamari Adhuri Kahani',
                composer: 'Jeet Ganguly',
                producer: 'Sony Music',
                productionDate: '09-AUG-2022',
                awards: '',
                lyrics: [
                    'Paas Aaye.. Dooriyaan Phir Bhi Kam Naa Hui',
                    'Ek Adhuri Si Hamari Kahani Rahi',
                    'Aasmaan Ko Zameen, Ye Zaroori Nahi',
                    'Jaa Mile.. Jaa Mile',
                    'Ishq Saccha Wahi',
                    'Jisko Milti Nahin Manzilein, Manzilein',
                    '',
                    'Rang Thhe, Noor Tha',
                    'Jab Kareeb Tu Tha',
                    'Ek Jannat Saa Tha, Yeh Jahaan',
                    'Waqt Ki Raeth Pe',
                    'Kuch Mere Naam Sa',
                    'Likh Ke Chhod Gaya, Tu Kahaan',
                    '',
                    'Hamari Adhuri Kahani (X4)',
                    '',
                    'Khushbuon Se Teri Yunhi Takra Gaye',
                    'Chalte Chalte Dekho Na',
                    'Hum Kahaan Aa Gaye',
                    '',
                    'Jannatein Agar Yahin',
                    'Tu Dikhe Kyon Nahin',
                    'Chand Suraj Sabhi, Hain Yahaan',
                    'Intezar Tera Sadiyon Se Kar Raha',
                    'Pyaasi Baithi Hai Kab Se Yahaan',
                    '',
                    'Hamari Adhuri Kahani (X4)',
                    '',
                    'Pyaas Ka Ye Safar',
                    'Khatam Ho Jayega',
                    'Kuch Adhura Sa Jo Tha',
                    'Poora Ho Jaayega',
                    '',
                    'Jhuk Gaya Aasmaan',
                    'Mill Gaye Do Jahaan',
                    'Har Taraf Hai Milan Ka Samaa',
                    'Doliyaan Hain Saji, Khushbuein Har Kahin',
                    'Padhne Aaya Khuda Khud Yahaan',
                    '',
                    'Humari Adhuri Kahaani (X4)',
                ]
            }
        ]
    },
    {
        name: 'Sid Sriram',
        nationality: 'Indian',
        age: 32,
        id: '456',
        profileUrl: 'https://yt3.googleusercontent.com/O6t6Q6_ov8mh98aT40eyjuTKJ78NK60vc21pkXC7tDYz6eH0-AnXbWMuI-CsWDuyPbwRd3zN2aM=s900-c-k-c0x00ffffff-no-rj',
        songs: [
            {
                id: '456',
                title: 'Aaradhya',
                composer: 'Hesham Abdul Wahab',
                producer: 'Dil Raju',
                productionDate: '2023',
                awards: '',
                lyrics: [
                    'You’re My Sunshine',
                    'You’re My Moonlight',
                    'You’re Star In The Sky',
                    'Come With Me Now',
                    '',
                    'You Have My Desire',
                    'Naatho Ra Neela Ra',
                    'Aradhya',
                    '',
                    'Padhamu Nee Vaipilaa',
                    'Parugu Needhe Kadhaa',
                    'Thanuvu Thera Meedhuga',
                    'Cheruko Twaragaa',
                    '',
                    'Manasara Chelithara',
                    'Na Gundeni Motham Thavvi Thavvi',
                    'Chandhanamantha Challaga Dhochave',
                    'Ye Vandhala Koddhi Pandaga Lunna',
                    'Vennela Motham Ninduga Unna',
                    '',
                    'Aradhya Na Aradhya',
                    'Nuvve Lenidhedhi Vaddhu',
                    'Aradhya',
                    '',
                    'Aradhya Na Aradhya',
                    'Nuvve Lenidhedhi Vaddhu',
                    'Aradhya',
                    '',
                    'Ee Poota Naa Paata',
                    'Cheraali Nee Dhaaka',
                    'Nee Chinni Meda Vampulo',
                    '',
                    'Saagali Ee Aata',
                    'Thedaalu Thelaaka',
                    'Gelichedhi Yevaremito',
                    '',
                    'Ilaage Untaale',
                    'Neethone Dhooraalu',
                    'Theeraalu Leve',
                    '',
                    'Aradhya Na Aradhya',
                    'Nuvve Lenidhedhi Vaddhu',
                    'Aradhya',
                    '',
                    'Aradhya Na Aradhya',
                    'Nuvve Lenidhedhi Vaddhu',
                    'Aradhya',
                    '',
                    'Yedho Anaalandhi',
                    'Inka Vinaalandhi',
                    'Nee Ooha Mallimpulo',
                    '',
                    'Naa Dhaaka Cherindhi',
                    'Naa Kuda Baagundhi',
                    'Nee Prema Kavvimpulo',
                    '',
                    'Nee Laane',
                    'Maraane',
                    'Antaane',
                    '',
                    'Nuvvantu Nenantu Leme',
                    '',
                    'Manasara Chelithara',
                    'Na Gundeni Motham Thavvi Thavvi',
                    'Chandhanamantha Challaga Dhochave',
                    'Ye Vandhala Koddhi Pandaga Lunna',
                    'Vennela Motham Ninduga Unna',
                    '',
                    'Aradhya Na Aradhya',
                    'Nuvve Lenidhedhi Vaddhu',
                    'Aradhya',
                    '',
                    'Aradhya Na Aradhya',
                    'Nuvve Lenidhedhi Vaddhu',
                    'Aradhya',
                    '',
                    'Padhamu Nee Vaipilaa',
                    'Parugu Needhe Kadhaa',
                    'Thanuvu Thera Meedhuga',
                    'Cheruko Twaragaa',
                ]
            },
            {
                id: '567',
                title: 'Nijame Ne Chebuthunna',
                composer: 'Shekar Chandra',
                producer: 'Razesh Danda',
                productionDate: '2023',
                awards: '',
                lyrics: [
                    'Nijame ne chebutunna jaane jaana',
                    'Ninne ne premistunna',
                    'Nijame ne chebuthunna yedhemaina',
                    'Na pranam needhantunna',
                    '',
                    'Vellake wadhililellake',
                    'Na gundeni dhochesila',
                    'Challake vedha challake',
                    'Na chuttu rangulnila',
                    '',
                    'Vennela theluse',
                    'Naaku varsham theluse',
                    'Ninu kalisake',
                    'Vennela varsham theluse',
                    '',
                    'Maunam theluse',
                    'Naaku maata theluse',
                    'Maunamlo dhagunde',
                    'Maatalu theluse',
                    '',
                    'Kannulatho choosedhi konchamey',
                    'Gundello lothe kanipincheney',
                    'Paipaina roopalu kaadhuley',
                    'Lolopali preme choodaliley',
                    '',
                    'Nijame ne chebutunna jaane jaana',
                    'Ninne ne premistunna',
                    'Nijame ne chebuthunna yedhemaina',
                    'Na pranam needhantunna',
                    '',
                    'Pedhavula thoti piliche pilupula kanna',
                    'Manasara o saige chalantunna',
                    'Adugulathoti dhuram koliche kanna',
                    'Dhuranne gurthinchani payanam kaana',
                    '',
                    'Needalle vasthaane neejathayi',
                    'Thodalle vuntaane neekathayi',
                    'O inupa palakanti gundepayi',
                    'Kavithalni rasavu dhevathayi',
                    '',
                    'Nijame ne chebutunna jaane jaana',
                    'Ninne ne premistunna',
                    'Nijame ne chebuthunna yedhemaina',
                    'Na pranam needhantunna',
                ]
            },
        ]
    },
    {
        name: 'Arman Malik',
        nationality: 'Indian',
        age: 28,
        id: '567',
        profileUrl: 'https://reservemystar.com/wp-content/uploads/2022/05/Armman-Malik.jpg',
        songs: [
            {
                id: '678',
                title: 'Butta Bomma',
                composer: 'S.S.Thaman',
                producer: 'Geetha Arts',
                productionDate: '2020',
                awards: '',
                lyrics: [
                    'Inthakanna Manchi Polikedi',
                    'Naaku Thattaledu Gaani Ammu',
                    '',
                    'Ee Love Anedi Bubble-u Gum-mu',
                    'Antukunnadhante Podhu Nammu',
                    '',
                    'Mundu Nunchi Andharanana Maate Gaani',
                    'Malli Anatanaane Ammu',
                    'Idhi Cheppakunda Vache Thummo',
                    'Premanaapaleru Nannu Nammu',
                    '',
                    'Ettaga Anaee Yeduru Choopuki',
                    'Thaginattuga Nuvvu Badhulu Chebithive',
                    'Arey Devuda, Idhendhanentha Lopate',
                    'Pilladanta Deggarayi Nannu Cheradheestive',
                    '',
                    'Butta Bomma, Butta Bomma',
                    'Nannu Suttukuntive',
                    'Zindagike Atta Bommayi',
                    'Janta Kattukuntive',
                    '',
                    'Buttabomma, Buttabomma Nannu Suttukuntive',
                    'Zindagi-Ke Atta Bommai Janta Kattu Kuntive',
                    '',
                    '[Instrumental Break]',
                    'Multiplex Loni Audience Laga',
                    'Mounamguna Gani Ammu',
                    'Lona Dandanaka Jariginde Nammu',
                    'Dimma Diriginaade Mind Sim-mu',
                    '',
                    '[Instrumental Music Continues]',
                    '',
                    'Rajula Kalam Kaadhu',
                    'Rathamo Gurran Levu',
                    'Addhan Mundara Natho Nene',
                    'Yudham Chestaante',
                    '',
                    'Gaajula Chethulu Jaapi',
                    'Deggarakochina Nuvvu',
                    'Chеpallo Chitikesi, Chakkaravarthini Chesave',
                    '',
                    'Chinnaga Chinnkku Thumparadigithе',
                    'Kundapothaga Tufaan-u Thestive',
                    'Maataga O Malle Poovunadigithe',
                    'Mootaga Pola Thotaga, Painochi Padithive',
                    '',
                    'Butta Bomma, Butta Bomma Nannu Suttukuntive',
                    'Zindagi-Ke Atta Bommai Janta Kattu Kuntive',
                    '',
                    'Veli Ninda Nannu Theesi',
                    'Bottu Pettukuntive',
                    'Kaali Kindi Puvvu Nenu Nethinetu Kuntive',
                    'You might also like',
                    'Anuv Jain - Baarishein (Romanized)',
                    'Genius Romanizations',
                    'Lose Yourself',
                    'Eminem',
                    'Anuv Jain - Husn (English Translation)',
                    'Genius English Translations',
                    'Inthakanna Manchi Polikedi',
                    'Naaku Thattaledu Gaani Ammu',
                    'Ee Love Anedi Bubble-u Gum-mu',
                    'Antukunnadhante Podhu Nammu',
                    '',
                    'Mundu Nunchi Andharanana Maate Gaani',
                    'Malli Anatanaane Ammu',
                    'Idhi Cheppakunda Vache Thummo',
                    'Premanapaleru Nannu Nammu',
                ]
            },
        ]
    },
    {
        name: 'Charlie Puth',
        nationality: 'American',
        age: 33,
        id: '678',
        profileUrl: 'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/866126_v9_bc.jpg',
        songs: [
            {
                id: '789',
                title: 'Attention',
                composer: 'Charlie Puth',
                producer: 'Charlie Puth',
                productionDate: '2017',
                awards: '',
                lyrics: [
                    'Oh-oh, ooh',
                    'You"ve been runnin" "round, runnin" "round, runnin" "round throwin" that dirt all on my name',
                    '"Cause you knew that I, knew that I, knew that I"d call you up',
                    'You"ve been going "round, going "round, going "round every party in L.A.',
                    '"Cause you knew that I, knew that I, knew that I"d be at one, oh',
                    'I know that dress is karma, perfume regret',
                    'You got me thinking "bout when you were mine, oh',
                    'And now I"m all up on ya, what you expect?',
                    'But you"re not coming home with me tonight',
                    'You just want attention, you don"t want my heart',
                    'Maybe you just hate the thought of me with someone new',
                    'Yeah, you just want attention, I knew from the start',
                    'You"re just making sure I"m never gettin" over you',
                    'you"ve been runnin" "round, runnin" "round, runnin" "round throwing that dirt all on my name',
                    '"Cause you knew that I, knew that I, knew that I"d call you up',
                    'Baby, now that we"re, now that we"re, now that we"re right here standing face-to-face',
                    'You already know, already know, already know that you won, oh',
                    'I know that dress is karma (dress is karma), perfume regret',
                    'You got me thinking "bout when you were mine (you got me thinking "bout when you were mine)',
                    'And now I"m all up on ya (all up on ya), what you expect? (oh baby)',
                    'But you"re not coming home with me tonight (oh no)',
                    'You just want attention, you don"t want my heart',
                    'Maybe you just hate the thought of me with someone new',
                    'Yeah, you just want attention, I knew from the start',
                    'You"re just making sure I"m never gettin" over you, oh',
                    'What are you doin" to me, what are you doin", huh?',
                    '(What are you doin"?)',
                    'What are you doin" to me, what are you doin", huh?',
                    '(What are you doin"?)',
                    'What are you doin" to me, what are you doin", huh?',
                    '(What are you doin"?)',
                    'What are you doin" to me, what are you doin", huh?',
                    'I know that dress is karma, perfume regret',
                    'You got me thinking "bout when you were mine',
                    'And now I"m all up on ya, what you expect?',
                    'But you"re not coming home with me tonight',
                    'You just want attention, you don"t want my heart',
                    'Maybe you just hate the thought of me with someone new',
                    'Yeah, you just want attention, I knew from the start',
                    'You"re just making sure I"m never gettin" over you (over you)',
                    'What are you doin" to me? (hey) what are you doin", huh? (what are you doin", what?)',
                    'What are you doin", huh? (what are you doin" to me?)',
                    '(What are you doin", huh?) (yeah, you just want attention)',
                    'What are you doin" to me, what are you doin", huh? (I knew from the start)',
                    '(You"re just making sure I"m never gettin" over you) what are you doin" to me, what are you doin", huh?',
                    'Oh, oh',
                ]
            },
            {
                id: '790',
                title: 'We Dont Talk Anymore',
                composer: 'Charlie Puth',
                producer: 'Charlie Puth',
                productionDate: '2016',
                awards: '',
                lyrics: [
                    'We don"t talk anymore',
                    'We don"t talk anymore',
                    'We don"t talk anymore',
                    'Like we used to do',
                    'We don"t love anymore',
                    'What was all of it for?',
                    'Oh, we don"t talk anymore',
                    'Like we used to do',
                    'I just heard you found the one you"ve been looking',
                    'You"ve been looking for',
                    'I wish I would have known that wasn"t me',
                    '"Cause even after all this time, I still wonder',
                    'Why I can"t move on',
                    'Just the way you did so easily',
                    'Don"t wanna know',
                    'Kind of dress you"re wearing tonight',
                    'If he"s holding onto you so tight',
                    'The way I did before',
                    'I overdosed',
                    'Should"ve known your love was a game',
                    'Now I can"t get you out of my brain',
                    'Oh, it"s such a shame',
                    'That we don"t talk anymore',
                    'We don"t talk anymore',
                    'We don"t talk anymore',
                    'Like we used to do',
                    'We don"t love anymore',
                    'What was all of it for?',
                    'Oh, we don"t talk anymore',
                    'Like we used to do',
                    'I just hope you"re lying next to somebody',
                    'Who knows how to love you like me',
                    'There must be a good reason that you"re gone',
                    'Every now and then I think you might want me to',
                    'Come show up at your door',
                    'But I"m just too afraid that I"ll be wrong',
                    'Don"t wanna know',
                    'If you"re looking into her eyes',
                    'If she"s holding onto you so tight',
                    'The way I did before',
                    'I overdosed',
                    'Should"ve known your love was a game',
                    'Now I can"t get you out of my brain',
                    'Oh, it"s such a shame',
                    'That we don"t talk anymore',
                    'We don"t talk anymore',
                    'We don"t talk anymore',
                    'Like we used to do',
                    'We don"t love anymore',
                    'What was all of it for?',
                    'Oh, we don"t talk anymore',
                    'Like we used to do',
                    'Like we used to do',
                    'Don"t wanna know',
                    'Kind of dress you"re wearing tonight',
                    'If he"s giving it to you just right',
                    'The way I did before',
                    'I overdosed',
                    'Should"ve known your love was a game',
                    'Now I can"t get you out of my brain',
                    'Oh, it"s such a shame',
                    'That we don"t talk anymore',
                    'We don"t talk anymore',
                    'We don"t talk anymore',
                    'Like we used to do',
                    'We don"t love anymore',
                    'What was all of it for?',
                    'Oh, we don"t talk anymore',
                    'Like we used to do',
                    'We don"t talk anymore (don"t wanna know)',
                    'Kind of dress you"re wearing tonight (oh)',
                    'If he"s holding onto you so tight (oh)',
                    'The way I did before',
                    'We don"t talk anymore (I overdosed)',
                    'Should"ve known your love was a game (oh)',
                    'Now I can"t get you out of my brain (whoa)',
                    'Oh, it"s such a shame',
                    'That we don"t talk anymore',
                ]
            },
        ]
    },
    {
        name: 'Ed Sheeran',
        nationality: 'American',
        age: 32,
        id: '789',
        profileUrl: 'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSC5dHXTqKJqX5YeHlzNtNAXWv2owk3fLLBtUOl_CBvnhBLEZiavi1KVYa-Q-6WSpzxVtgbOVZDdXJqi9M',
        songs: [
            {
                id: '811',
                title: 'Perfect',
                composer: 'Ed Sheeran',
                producer: 'Ed Sheeran',
                productionDate: '2017',
                awards: 'Radio Disney Music Award for Best Crush Song 2018, Teen Choice Award for Choice Single: Male Artist 2018, MuchMusic Video Award for Single of the Year 2018',
                lyrics: [
                    'I found a love, for me',
                    'Darling, just dive right in and follow my lead',
                    'Well, I found a girl, beautiful and sweet',
                    'Oh, I never knew you were the someone waiting for me',
                    '"Cause we were just kids when we fell in love',
                    'Not knowing what it was',
                    'I will not give you up this time',
                    'But darling, just kiss me slow',
                    'Your heart is all I own',
                    'And in your eyes, you"re holding mine',
                    'Baby, I"m dancing in the dark',
                    'With you between my arms',
                    'Barefoot on the grass',
                    'Listening to our favourite song',
                    'When you said you looked a mess',
                    'I whispered underneath my breath',
                    'But you heard it',
                    'Darling, you look perfect tonight',
                    'Well, I found a woman, stronger than anyone I know',
                    'She shares my dreams, I hope that someday I"ll share her home',
                    'I found a lover, to carry more than just my secrets',
                    'To carry love, to carry children of our own',
                    'We are still kids, but we"re so in love',
                    'Fighting against all odds',
                    'I know we"ll be alright this time',
                    'Darling, just hold my hand',
                    'Be my girl, I"ll be your man',
                    'I see my future in your eyes',
                    'Baby, I"m dancing in the dark',
                    'With you between my arms',
                    'Barefoot on the grass',
                    'Listening to our favorite song',
                    'When I saw you in that dress, looking so beautiful',
                    'I don"t deserve this',
                    'Darling, you look perfect tonight',
                    'Baby, I"m dancing in the dark',
                    'With you between my arms',
                    'Barefoot on the grass',
                    'Listening to our favorite song',
                    'I have faith in what I see',
                    'Now I know I have met an angel in person',
                    'And she looks perfect',
                    'I don"t deserve this',
                    'You look perfect tonight',
                ]
            },
            {
                id: '812',
                title: 'Shape Of You',
                composer: 'Ed Sheeran',
                producer: 'Ed Sheeran',
                productionDate: '2017',
                awards: 'NRJ Music Award for Most Streamed Song 2017, Grammy Award for Best Pop Solo Performance 2018',
                lyrics: [
                    'The club isn"t the best place to find a lover',
                    'So the bar is where I go',
                    'Me and my friends at the table doing shots',
                    'Drinking fast and then we talk slow',
                    'Come over and start up a conversation with just me',
                    'And trust me I"ll give it a chance now',
                    'Take my hand, stop, put Van the Man on the jukebox',
                    'And then we start to dance, and now I"m singing like',
                    'Girl, you know I want your love',
                    'Your love was handmade for somebody like me',
                    'Come on now, follow my lead',
                    'I may be crazy, don"t mind me',
                    'Say, boy, let"s not talk too much',
                    'Grab on my waist and put that body on me',
                    'Come on now, follow my lead',
                    'Come, come on now, follow my lead',
                    'I"m in love with the shape of you',
                    'We push and pull like a magnet do',
                    'Although my heart is falling too',
                    'I"m in love with your body',
                    'And last night you were in my room',
                    'And now my bedsheets smell like you',
                    'Every day discovering something brand new',
                    'I"m in love with your body',
                    '(Oh-I-oh-I-oh-I-oh-I)',
                    'I"m in love with your body',
                    '(Oh-I-oh-I-oh-I-oh-I)',
                    'I"m in love with your body',
                    '(Oh-I-oh-I-oh-I-oh-I)',
                    'I"m in love with your body',
                    'Every day discovering something brand new',
                    'I"m in love with the shape of you',
                    'One week in we let the story begin',
                    'We"re going out on our first date',
                    'You and me are thrifty, so go all you can eat',
                    'Fill up your bag and I fill up a plate',
                    'We talk for hours and hours about the sweet and the sour',
                    'And how your family is doing okay',
                    'And leave and get in a taxi, then kiss in the backseat',
                    'Tell the driver make the radio play, and I"m singing like',
                    'Girl, you know I want your love',
                    'Your love was handmade for somebody like me',
                    'Come on now, follow my lead',
                    'I may be crazy, don"t mind me',
                    'Say, boy, let"s not talk too much',
                    'Grab on my waist and put that body on me',
                    'Come on now, follow my lead',
                    'Come, come on now, follow my lead',
                    'I"m in love with the shape of you',
                    'We push and pull like a magnet do',
                    'Although my heart is falling too',
                    'I"m in love with your body',
                    'And last night you were in my room',
                    'And now my bedsheets smell like you',
                    'Every day discovering something brand new',
                    'I"m in love with your body',
                    '(Oh-I-oh-I-oh-I-oh-I)',
                    'I"m in love with your body',
                    '(Oh-I-oh-I-oh-I-oh-I)',
                    'I"m in love with your body',
                    '(Oh-I-oh-I-oh-I-oh-I)',
                    'I"m in love with your body',
                    'Every day discovering something brand new',
                    'I"m in love with the shape of you',
                    'Come on, be my baby, come on',
                    'Come on, be my baby, come on',
                    'Come on, be my baby, come on',
                    'Come on, be my baby, come on',
                    'Come on, be my baby, come on',
                    'Come on, be my baby, come on',
                    'Come on, be my baby, come on',
                    'Come on, be my baby, come on',
                    'I"m in love with the shape of you',
                    'We push and pull like a magnet do',
                    'Although my heart is falling too',
                    'I"m in love with your body',
                    'And last night you were in my room',
                    'And now my bedsheets smell like you',
                    'Every day discovering something brand new',
                    'I"m in love with your body',
                    'Come on, be my baby, come on',
                    'Come on (I"m in love with your body), be my baby, come on',
                    'Come on, be my baby, come on',
                    'Come on (I"m in love with your body), be my baby, come on',
                    'Come on, be my baby, come on',
                    'Come on (I"m in love with your body), be my baby, come on',
                    'Every day discovering something brand new',
                    'I"m in love with the shape of you',
                ]
            },
            {
                id: '823',
                title: 'Photograph',
                composer: 'Ed Sheeran',
                producer: 'Ed Sheeran',
                productionDate: '2014',
                awards: '',
                lyrics: [
                    'Loving can hurt, loving can hurt sometimes',
                    'But it"s the only thing that I know',
                    'When it gets hard, you know it can get hard sometimes',
                    'It is the only thing makes us feel alive',
                    'We keep this love in a photograph',
                    'We made these memories for ourselves',
                    'Where our eyes are never closing',
                    'Hearts are never broken',
                    'And time"s forever frozen still',
                    'So you can keep me',
                    'Inside the pocket of your ripped jeans',
                    'Holding me closer "til our eyes meet',
                    'You won"t ever be alone, wait for me to come home',
                    'Loving can heal, loving can mend your soul',
                    'And it"s the only thing that I know, know',
                    'I swear it will get easier',
                    'Remember that with every piece of ya',
                    'Hmm, and it"s the only thing we take with us when we die',
                    'Hmm, we keep this love in this photograph',
                    'We made these memories for ourselves',
                    'Where our eyes are never closing',
                    'Hearts were never broken',
                    'And time"s forever frozen, still',
                    'So you can keep me',
                    'Inside the pocket of your ripped jeans',
                    'Holding me closer "til our eyes meet',
                    'You won"t ever be alone',
                    'And if you hurt me',
                    'That"s okay, baby, only words bleed',
                    'Inside these pages, you just hold me',
                    'And I won"t ever let you go',
                    'Wait for me to come home',
                    'Wait for me to come home',
                    'Wait for me to come home',
                    'Wait for me to come home',
                    'Oh, you can fit me',
                    'Inside the necklace you got when you were sixteen',
                    'Next to your heartbeat where I should be',
                    'Keep it deep within your soul',
                    'And if you hurt me',
                    'Well, that"s okay, baby, only words bleed',
                    'Inside these pages, you just hold me',
                    'And I won"t ever let you go',
                    'When I"m away, I will remember how you kissed me',
                    'Under the lamppost back on Sixth street',
                    'Hearing you whisper through the phone',
                    '"Wait for me to come home"',
                ]
            },
        ]
    },
]